-- Supabase SQL Editor에 이 파일 전체를 복사해서 실행하세요.
-- (테이블은 이미 만들어져 있다면 1)번은 건너뛰고 그대로 실행해도 안전합니다 - if not exists)

-- 1) 표 만들기: 손님들이 남긴 "오늘의 한마디"를 저장하는 표
create table if not exists lines (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nikname text not null,
  message text not null
);

-- 1-1) user_id 칸 추가: 어떤 브라우저(손님)가 남겼는지 구분하기 위한 칸
--      (로그인이 없으므로 auth 사용자와는 무관 - 클라이언트에서 만든 익명 id를 저장)
alter table lines add column if not exists user_id uuid;

-- 2) 보안(RLS) 켜기: 켜야 아래 3)번 정책이 의미를 가짐
alter table lines enable row level security;

-- 3) 정책 만들기: 로그인 없는 손님(anon)도 읽고 쓸 수 있게 허용
--    (update, delete는 정책을 만들지 않아 자동으로 막힘)
create policy "누구나 목록을 볼 수 있음"
  on lines for select
  to anon
  using (true);

create policy "누구나 한마디를 남길 수 있음"
  on lines for insert
  to anon
  with check (true);
